### ISSUE TITLE
add all bot and implement lookup

### ISSUE THREAD

**Issue by karrybit** [TakumiKaribe/multilingo#19]
- C
- C++
- C#
- Java
- Python3
- Ruby
- JavaScript
- Scala
- Go
- Haskell
- Rust
- Swift
- Kotlin

**Comment by karrybit** [comment]
Cっているか？？？？C++あればよくね？？？？

**Comment by 44smkn** [comment]
@TakumiKaribe  
んーいらないかもしれないです。
絵文字無いのに、なんとなくの感覚で入れてしまいました。
